### PR TITLE
Added Quick Sort Algo in Python

### PR DESCRIPTION
**Pull request by Hritik-Verma41**
Added the quick sort algorithm in python. Issue #2

### CODE REVIEW

**Comment by jatinkumar027** [comment]
Have you tested the code. Is the output coming as expected?

**Comment by Hritik-Verma41** [comment]
yes, do you need any screenshots?

**Comment by Hritik-Verma41** [comment]
image

**Comment by jatinkumar027** [comment]
Great. 👍 😊

**Comment by Hritik-Verma41** [comment]
thank you @jatinkumar027

**Comment by jatinkumar027** [comment]
You are welcome. Make sure to star the repository for future contributions 😊

**Pull request merged**
