### PR TITLE
uncommon words in two string

### LINKED ISSUE #16: Replace all occurrences of a substring in a string
Definition of done:

1. Clear code should be written.
2. Comments will be really appreciable.
3. Add minimum 2 test cases to test the code.
4. Add you code under Python/Data Structure and Algorithms/<ProgramName.py>
5. Make sure to add the Screenshot of Program Testing in the comment while merging the PR

### PR DESCRIPTION
**Pull request by Danuragtiwari**
Added python program to find uncommon words in two string check it

### CODE REVIEW

**Comment by Danuragtiwari** [comment]
@jatinkumar027 check it sir

**Comment by jatinkumar027** [comment]
Please add the screenshot of the terminal output

**Comment by Danuragtiwari** [comment]
Screenshot (553)

**Comment by jatinkumar027** [comment]
Great. Please add the output screenshot

**Comment by jatinkumar027** [comment]
Please wait for 3-5 seconds for the screenshot to be uploaded and then press the comment button

**Comment by Danuragtiwari** [comment]
sir it not uploading don't what may be the issue.

**Comment by jatinkumar027** [comment]
No Problem I think I received the output on my email thread. Merging the changes

**Review by jatinkumar027 — APPROVED** [review]
approved

**Review by jatinkumar027 — APPROVED** [review]

**Review by jatinkumar027 — APPROVED** [review]

**Pull request merged**
