### PR TITLE
Created File selectionSort.py

### PR DESCRIPTION
**Pull request by ashishpetwal**
Hey, @jatinkumar027  I have created a selection sort file in python and solved issue #28 . This implements one of the beautiful sorting technique "Selection Sort". I have attached the output of program in my system.
Kindly merge and close the issue...

### CODE REVIEW

**Comment by ashishpetwal** [comment]
Screenshot (27)

**Comment by ashishpetwal** [comment]
Screenshot (28)

**Comment by jatinkumar027** [comment]
Great work @ashishpetwal

**Review by jatinkumar027 — APPROVED** [review]
approved

**Pull request merged**
