### PR TITLE
Added checkStringForAllVowels code

### PR DESCRIPTION
**Pull request by Kunal-Garg-12**
Checks if a given string contains all vowels
Issue: https://github.com/jatinkumar027/Nourishing-Skills/issues/9

Signed-off-by: Kunal Garg <kunalgarg2002@gmail.com>

### CODE REVIEW

**Comment by jatinkumar027** [comment]
I think by mistake you have added the .ipynb file. Please add the python file with .py extension

**Comment by Kunal-Garg-12** [comment]
I added ipynb file as I did it in jupyter notebook which is a good IDE for python beginners. It can be opened in VS Code. I can change it to .py file if you still want that.

**Comment by jatinkumar027** [comment]
I request you to add simple python code here. You can take the reference of the sample code already present in repository

**Comment by Kunal-Garg-12** [comment]
Updated as required. Please check

**Comment by jatinkumar027** [comment]
Great. Merging

**Review by jatinkumar027 — APPROVED** [review]

**Pull request merged**
